name: nautograf
base: core22
adopt-info: nautograf
summary: Tile-based nautical chart viewer
description: >
  Nautograf is a viewer for marine vector charts. It is inspired by
  OpenCPN which is the only nautical chart software that is open
  source and runs with offline chart data. Nautograf only supports
  chart data from https://www.o-charts.org. Please visit the GitHub
  repository for more information: https://github.com/hornang/nautograf
grade: stable
confinement: strict
apps:
  nautograf:
    command-chain:
    - bin/graphics-core22-wrapper
    command: usr/bin/nautograf
    extensions: [gnome]
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins
      QML2_IMPORT_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/qml

      # Disable wayland to get proper Gnome window borders.
      # DISABLE_WAYLAND is picked up by the desktop-launch script in
      # gnome content snap
      DISABLE_WAYLAND: 1
    plugs:
      - home

# Statements related to mesa-core22 is from this forum post:
# https://discourse.ubuntu.com/t/the-graphics-core22-snap-interface/34663

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d

parts:
  nautograf:
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags | sed 's/^v\?\(.*\)$/\1/')
    source: .
    plugin: cmake
    build-environment:
      - VCPKG_FORCE_SYSTEM_BINARIES: 1 # Must be set for building on arm
    cmake-parameters:
      - -DCMAKE_TOOLCHAIN_FILE=${CRAFT_PART_SRC}/vcpkg/scripts/buildsystems/vcpkg.cmake
      - -DBUILD_TESTING=off
      - -DUSE_XDG_FILE_DIALOG=on
      - -DUSE_OEXSERVERD=off
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      # curl, zip, unzip and tar is needed by vcpkg:
      # https://github.com/microsoft/vcpkg/blob/master/scripts/bootstrap.sh#L88-L91
      - curl
      - zip
      - unzip
      - tar

      - build-essential
      - ninja-build
      - libglu1-mesa-dev
      - libxmu-dev
      - libxi-dev
      - libgl-dev
      - imagemagick
      - librsvg2-bin
      - qt6-base-dev
      - qt6-declarative-dev
      - libqt6shadertools6-dev
      - libqt6svg6-dev
      - libqt6opengl6-dev
      - pkg-config

    stage-packages:
      - libqt6core6
      - libqt6gui6
      - libqt6opengl6
      - libqt6qmlmodels6
      - libqt6quick6
      - libqt6widgets6
      - libqt6svg6
      - qt6-qpa-plugins
      - qt6-gtk-platformtheme
      - qml6-module-qtquick-controls
      - qml6-module-qtquick-layouts
      - qml6-module-qtquick-window
      - qml6-module-qt-labs-platform
      - qml6-module-qtqml-workerscript
      - qml6-module-qtquick-templates

  graphics-core22:
    after: [nautograf]
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
    - bin/graphics-core22-wrapper
