name: nautograf
base: core22
adopt-info: nautograf
summary: Tile-based nautical chart viewer
description: >
  Nautograf is a viewer for marine vector charts. It is inspired by
  OpenCPN which is the only nautical chart software that is open
  source and runs with offline chart data. The motivation with
  Nautograf is to provide an application similar to OpenCPN, but
  provide a smoother zooming and panning experience, better
  rendering quality and in general a more modern code base.
grade: devel
confinement: devmode
apps:
  nautograf:
    command-chain:
    - bin/graphics-core22-wrapper
    command: usr/bin/nautograf
    environment:
      QT_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt6/plugins
      QML2_IMPORT_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt6/qml

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts

parts:
  nautograf:
    override-pull: |
      snapcraftctl pull
      craftctl set version="$(git describe --tags)"
    source: .
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_TOOLCHAIN_FILE=${CRAFT_PART_SRC}/vcpkg/scripts/buildsystems/vcpkg.cmake
      - -DBUILD_TESTING=off
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - libglu1-mesa-dev
      - libxmu-dev
      - libxi-dev
      - libgl-dev
      - imagemagick
      - librsvg2-bin
      - qt6-base-dev
      - qt6-declarative-dev
      - libqt6shadertools6-dev
      - libqt6svg6-dev
      - libqt6opengl6-dev
      - zip
      - pkg-config

    stage-packages:
      - libqt6core6
      - libqt6gui6
      - libqt6opengl6
      - libqt6qmlmodels6
      - libqt6quick6
      - libqt6widgets6
      - qt6-qpa-plugins
      - qml6-module-qtquick-controls
      - qml6-module-qtquick-layouts
      - qml6-module-qtquick-window
      - qml6-module-qt-labs-platform
      - qml6-module-qtqml-workerscript
      - qml6-module-qtquick-templates
      - fonts-ubuntu

  graphics-core22:
    after: [nautograf]
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
    - bin/graphics-core22-wrapper
