name: Build packages

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  Windows:
    runs-on: windows-latest
    env:
      buildDir: '${{ github.workspace }}/build'

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.1'
          arch: 'win64_msvc2019_64'
          modules: "qtshadertools"

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10

      - name: Install choco dependencies
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install chocolatey.config -y --no-progress

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'win-release'

      - name: Run cpack
        run: cd builds/ninja-multi-vcpkg; cpack -C Release

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: |
            builds/ninja-multi-vcpkg/_CPack_Packages/win64/ZIP
            !builds/ninja-multi-vcpkg/_CPack_Packages/win64/ZIP/*.zip
