name: Build packages

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
    branches:
      - main

  schedule:
    - cron: '30 10 * * 0'

jobs:
  Windows:
    runs-on: windows-latest
    env:
      SYSTEM_NAME: win64

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.1'
          cache: true
          arch: 'win64_msvc2019_64'
          modules: "qtshadertools"

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v11

      - name: Install choco dependencies
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install chocolatey.config -y --no-progress

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'release'

      - name: Install to directory
        shell: bash
        run: >
          cd "${{ github.workspace }}/builds/ninja-multi-vcpkg";
          PACKAGE_NAME=nautograf-$(cat version.txt)-$SYSTEM_NAME;
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV;
          cmake --install . --config Release --prefix "$(pwd)/install/$PACKAGE_NAME"

      - name: Deploy Qt libraries to install dir
        shell: bash
        run: >
          cmake -DEXECUTABLE_DIR="${{ github.workspace }}/builds/ninja-multi-vcpkg/install/${{ env.PACKAGE_NAME }}/bin"
          -P "${{ github.workspace }}/builds/ninja-multi-vcpkg/deploy-qt-windows.cmake"

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ github.workspace }}/builds/ninja-multi-vcpkg/install

  ubuntu-20-04:
    name: 'Ubuntu 20.04'
    runs-on: ubuntu-20.04
    env:
      SYSTEM_NAME: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.1'
          cache: 'true'
          modules: 'qtshadertools'

      - name: Install dependencies
        run: sudo apt-get install libglu1-mesa-dev libxmu-dev libxi-dev libgl-dev imagemagick librsvg2-bin

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v11

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg-static'
          buildPreset: 'static-release'

      - name: Install to directory
        shell: bash
        run: >
          cd "${{ github.workspace }}/builds/ninja-multi-vcpkg-static";
          PACKAGE_NAME=nautograf-$(cat version.txt)-$SYSTEM_NAME;
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV;
          cmake --install . --config Release --prefix "$(pwd)/install/$PACKAGE_NAME"

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: ${{ github.workspace }}/builds/ninja-multi-vcpkg-static/install
