on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    env:
      buildDir: '${{ github.workspace }}/build'

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ${{ runner.workspace }}/Qt
          key: ${{ runner.os }}-QtCache-6.2.0

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.2.0'
          arch: 'win64_msvc2019_64'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.3

      - name: Install choco dependencies
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install chocolatey.config -y --no-progress

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'ninja-multi-vcpkg'
          buildPreset: 'win-release'
